# Generated by Django 4.2.3 on 2023-07-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='content',
            field=models.TextField(null=True, verbose_name='내용'),
        ),
    ]
